# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9232ed39bed096d3f2464b83247ebc1e"
name = "Store Management"
application_url = "https://example.com"
embedded = true
handle = "store-management-helper"

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,write_metaobject_definitions,write_metaobjects,write_price_rules,write_products,write_themes"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
